# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', File.join(__dir__, "..", "js")]).strip

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
# Needed for Reanimated setup when iOS project is located outside of directory that contains node_modules
ENV['REACT_NATIVE_NODE_MODULES_DIR'] = File.realpath(File.join(__dir__, "..", "js", "node_modules"))

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'brownfieldtest' do
  command = ['node', '-e', "process.chdir('../js');process.argv=['', '', 'config'];require('../js/node_modules/@react-native-community/cli').run()"]
  config = use_native_modules!(command)

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/../js"
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
